name: Build WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  EM_VERSION: 1.39.18
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu Emscripten Debug",
            artifact: "wasm_debug.tar.xz",
            build_type: "debug",
          }
          - {
            name: "Ubuntu Emscripten Release",
            artifact: "wasm_release.tar.xz",
            build_type: "release",
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v9

      - name: Configure CMake
        run: |
          emcmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}} -j2

      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: build
          target-folder: ${{matrix.config.build_type}}

      - name: Prepare Upload
        run: |
          tar cfz ${{matrix.config.artifact}} build

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ${{matrix.config.artifact}}
          name: ${{matrix.config.artifact}}
